### ISSUE TITLE
About the specific SPEC CPU2006’s version?

### ISSUE THREAD

**Issue by zehui-cheng** [mustakcsecuet/OS-CFI#4]
I am a postgraduate from a university in China and I am currently reproducing your thesis. However,  I encountered a problem that the number of indirect calls are not the same as your sheet in your paper.(**I am testing under SPEC CPU2006 v1.2**)
    **Anyway, I would like to ask what is your specific version about the SPEC CPU2006? Hope to hear from you and wish you a happy life!**

**Comment by mustakimur** [comment]
@zehui-cheng I really cannot remember and also don't have the exact spec anymore in my access.
