### ISSUE TITLE
Hello, I am a Chinese university student and I want to use your project.However, a problem occurred during the test using

### ISSUE THREAD

**Issue by Pawn-xd** [mustakcsecuet/OS-CFI#5]
First of all, I'm very sorry that I downloaded your project without contacting you. In my graduation project I want to generate the CFG of the program, so I would like to see your generated CFG. I use ubuntu22.04 to compile the project. But the sample_exec compiled after I run test_run.sh cannot run normally, and the error message is similar: [Unexpected trap 13! at 0x402908(core dumped). And the cpp program I tested also has this problem. May I ask what the possible question is?where does the CFG exist?Thank you so much!

**Comment by mustakimur** [comment]
Hi
I understand the prototype is currently broken due to hardware (MPX) dependency. However, if you are only interested in CFG, take advantage of the dump functions from the SVF codes e.g. void DDAPass::dumpcCFG() `https://github.com/mustakimur/OS-CFI/blob/master/svf-src/lib/DDA/DDAPass.cpp`.

**Comment by Pawn-xd** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mustakimur/OS-CFI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月25日(星期六) 晚上8:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mustakimur/OS-CFI] Hello, I am a Chinese university student and I want to use your project.However, a problem occurred during the test using (Issue #5)





 
Hi
 I understand the prototype is currently broken due to hardware (MPX) dependency. However, if you are only interested in CFG, take advantage of the dump functions from the SVF codes e.g. void DDAPass::dumpcCFG() https://github.com/mustakimur/OS-CFI/blob/master/svf-src/lib/DDA/DDAPass.cpp.
